### ISSUE TITLE
AttributeError: 'int' object has no attribute 'name'

### ISSUE THREAD

**Issue by soultanis** [tigerjack/qiskit_grover#1]
When I want to run the example code ```gt.build_and_run(2, [3])``` on jupyter notebook, I get the error message: "AttributeError: 'int' object has no attribute 'name'".

**Comment by tigerjack** [comment]
Should be fixed in the latest commit c12beb7a

**Comment by soultanis** [comment]
That was fast, I appreciate it!

**Comment by tigerjack** [comment]
Don't get too used to it :D. By the way, I'll close the issue if it is fixed; if you still have problems, feel free to reopen.
